<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Boardmember Yearly Dashboard PDF</title>
    <link rel="stylesheet" href="{{ public_path('css/boardmember_pdf.css') }}">
    <style>
        .monthly-table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 12px;
        }
        .monthly-table thead {
            background: #1976d2;
            color: #fff;
        }
        .monthly-table th {
            padding: 8px;
            text-align: left;
            font-weight: 600;
            border: 1px solid #1976d2;
        }
        .monthly-table td {
            padding: 8px;
            border: 1px solid #e0e0e0;
        }
        .monthly-table tbody tr:nth-child(even) {
            background: #f9f9f9;
        }
        .text-right {
            text-align: right;
        }
        .bar {
            background: #e0e0e0;
            height: 10px;
            border-radius: 5px;
            margin: 6px 0;
        }
        .bar-blue {
            background: #1976d2;
            height: 10px;
            border-radius: 5px;
        }
        .small {
            font-size: 11px;
            color: #666;
        }
    </style>
</head>
<body>

<div style="text-align:center; margin-bottom:6px;">
    <img src="{{ public_path('images/SP Seal.png') }}" style="height:32px;">
</div>

<h1>Boardmember Yearly Dashboard</h1>

<div class="meta">
    <div><strong>Generated:</strong> {{ now()->format('F d, Y h:i A') }}</div>
    <div><strong>Year:</strong> {{ now()->year }} (January – December)</div>
</div>

@if($vehicle)
<div class="box">

    <h2>Vehicle Information</h2>
    <div><strong>Plate Number:</strong> {{ $vehicle->plate_number }}</div>
    <div><strong>Monthly Fuel Limit:</strong> {{ $monthlyLimit }} liters</div>

    <h2>Yearly Budget Overview</h2>
    <div><strong>Yearly Budget:</strong> ₱{{ number_format($yearlyBudget, 2) }}</div>
    <div><strong>Total Used:</strong> ₱{{ number_format($yearlyBudget - $remainingBudget, 2) }}</div>
    <div><strong>Remaining Budget:</strong> ₱{{ number_format($remainingBudget, 2) }}</div>
    <div><strong>Budget Used:</strong> {{ $budgetUsedPercentage }}%</div>

    <div class="bar">
        <div class="bar-blue" style="width: {{ min(max($budgetUsedPercentage,0),100) }}%;"></div>
    </div>

    {{-- ✅ GOVERNMENT-SAFE BUDGET LOGIC --}}
    <h2>Budget Recommendation</h2>

    @php
        $remainingPercent = 100 - $budgetUsedPercentage;
    @endphp

    @if($budgetUsedPercentage >= 90)
        <strong style="color:#c62828;">Increase Budget</strong>
        <p class="small">
            More than 90% of the annual budget has been utilized. Additional allocation may be required to sustain operations.
        </p>

    @elseif($remainingPercent >= 25 && $remainingPercent <= 30)
        <strong style="color:#2e7d32;">Maintain Budget</strong>
        <p class="small">
            Remaining budget is within the ideal savings range. Current allocation is sufficient.
        </p>

    @elseif($remainingBudget >= 30000)
        <strong style="color:#ef6c00;">Consider Decrease</strong>
        <p class="small">
            A significant portion of the budget remains unused. Reducing next year’s allocation may improve fiscal efficiency.
        </p>

    @else
        <strong>Monitor Usage</strong>
        <p class="small">
            Budget utilization is within acceptable limits. Continued monitoring is advised.
        </p>
    @endif

    <h2>Monthly Breakdown ({{ now()->year }})</h2>
    <table class="monthly-table">
        <thead>
            <tr>
                <th>Month</th>
                <th class="text-right">Liters Used</th>
                <th class="text-right">Cost (₱)</th>
            </tr>
        </thead>
        <tbody>
            @php($totalLiters = 0)
            @php($totalCost = 0)

            @foreach($monthlyData as $month)
                @php($totalLiters += $month['liters'])
                @php($totalCost += $month['cost'])
                <tr>
                    <td>{{ $month['month'] }}</td>
                    <td class="text-right">{{ number_format($month['liters'],2) }}</td>
                    <td class="text-right">₱{{ number_format($month['cost'],2) }}</td>
                </tr>
            @endforeach

            <tr style="font-weight:600;background:#f5f5f5;">
                <td>Total</td>
                <td class="text-right">{{ number_format($totalLiters,2) }}</td>
                <td class="text-right">₱{{ number_format($totalCost,2) }}</td>
            </tr>
        </tbody>
    </table>

    <h2>Summary Statistics</h2>
    <div><strong>Average Monthly Usage:</strong> {{ number_format($totalLiters / 12, 2) }} liters</div>
    <div><strong>Average Monthly Cost:</strong> ₱{{ number_format($totalCost / 12, 2) }}</div>

</div>
@else
<p>No vehicle assigned.</p>
@endif

<div style="margin-top:30px;font-size:11px;color:#666;text-align:center;">
    Official report generated by the BM Vehicle Monitoring System
</div>

</body>
</html>
